In [4]:
#***       NSE margin data for Equities       ***
# ______________________________________________

# Margins for equities extracted from the web-site:
# https://www.nseindia.com/archives/nsccl/var/C_VAR1_ddmmyyyy_1.DAT

import datetime
import requests
import pandas as pd

# Set date in the right format for today
dt = datetime.datetime.now().strftime('%d%m%Y')

url = 'https://www.nseindia.com/archives/nsccl/var/C_VAR1_'+dt+'_1.DAT'
page = requests.get(url).text

data = page.replace('\n', ';') # replaces the newline feeds

# Remove the first row, and split the data into columns
df_raw = pd.read_csv(pd.compat.StringIO(data), header=None, sep=';').T[1:][0].str.split(',', expand=True)
df_raw = df_raw.rename({0: 'RecType', 1: 'Symbol', 2: 'Series', 
               3: 'ISIN', 4: 'SecVaR', 5: 'IndexVaR',
               6: 'VaRMargin', 7: 'XLossRate', 8: 'AdhocMargin', 9: 'NSEMarginRate'}, axis=1)

# Convert the data into float %ge
fields = 'SecVaR,IndexVaR,VaRMargin,XLossRate,AdhocMargin,NSEMarginRate'.split(',')
df_raw[fields] = df_raw[fields].apply(pd.to_numeric).div(100)

df = df_raw[['Symbol', 'NSEMarginRate']]
df

          Symbol  NSEMarginRate
1      20MICRONS         0.1600
2     21STCENMGM         0.3098
3     3IINFOTECH         0.2774
4        3MINDIA         0.1250
5         3PLAND         1.0000
6         5PAISA         0.3105
7        63MOONS         0.2177
8        8KMILES         1.0000
9       A2ZINFRA         0.8000
10        AAKASH         0.4830
11         AARON         0.4830
12    AARTIDRUGS         0.1250
13      AARTIIND         0.1250
14     AARVEEDEN         0.3098
15         AARVI         0.4830
16         AAVAS         0.1338
17          ABAN         0.1529
18           ABB         0.1250
19    ABBOTINDIA         0.1250
20     ABCAPITAL         0.1446
21         ABFRL         0.1250
22       ABGSHIP         1.0000
23      ABHISHEK         0.4830
24     ABMINTLTD         1.0000
25    ABSLFTOWDG         0.4830
26    ABSLFTOWDN         0.4830
27    ABSLFTOWDQ         0.4830
28    ABSLFTOWRG         0.4830
29    ABSLFTOWRN         0.4830
30    ABSLFTOWRQ         0.4830
...          ...            ...
5582     WINSOME         0.3098
5583        WIPL         1.0000
5584       WIPRO         0.1250
5585  WOCKPHARMA         0.1830
5586    WONDERLA         0.1250
5587       WORTH         0.4899
5588         WSI         1.0000
5589  WSTCSTPAPR         0.1580
5590   XCHANGING         0.4121
5591    XLENERGY         1.0000
5592   XPROINDIA         0.3098
5593     YESBANK         0.2705
5594        ZEEL         0.1250
5595        ZEEL         0.1250
5596    ZEELEARN         0.1250
5597    ZEEMEDIA         0.1424
5598   ZENITHBIR         1.0000
5599  ZENITHEXPO         0.3197
5600  ZENSARTECH         0.1784
5601      ZENTEC         0.1771
5602       ZICOM         0.3185
5603      ZODIAC         0.4897
5604  ZODIACLOTH         0.3098
5605   ZODJRDMKJ         0.3382
5606        ZOTA         0.4830
5607       ZUARI         0.1402
5608   ZUARIGLOB         0.1515
5609   ZYDUSWELL         0.1250
5610       ZYLOG         1.0000
5611        None            NaN

[5611 rows x 2 columns]